/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as NewShowRouteImport } from './routes/new-show'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioSlugRouteImport } from './routes/studio.$slug'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const NewShowRoute = NewShowRouteImport.update({
  id: '/new-show',
  path: '/new-show',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSlugRoute = StudioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/new-show': typeof NewShowRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$slug': typeof StudioSlugRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/new-show': typeof NewShowRoute
  '/studio/$slug': typeof StudioSlugRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/new-show': typeof NewShowRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$slug': typeof StudioSlugRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/login'
    | '/new-show'
    | '/studio'
    | '/studio/$slug'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$slug' | '/login' | '/new-show' | '/studio/$slug' | '/studio'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/login'
    | '/new-show'
    | '/studio'
    | '/studio/$slug'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  LoginRoute: typeof LoginRoute
  NewShowRoute: typeof NewShowRoute
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-show': {
      id: '/new-show'
      path: '/new-show'
      fullPath: '/new-show'
      preLoaderRoute: typeof NewShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$slug': {
      id: '/studio/$slug'
      path: '/$slug'
      fullPath: '/studio/$slug'
      preLoaderRoute: typeof StudioSlugRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioSlugRoute: typeof StudioSlugRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioSlugRoute: StudioSlugRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  LoginRoute: LoginRoute,
  NewShowRoute: NewShowRoute,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
